#ifndef __METAL_PLATFORM__
#define __METAL_PLATFORM__

#define CLINT_IRQ_NUM   2
#define OS_HWI_MAX_NUM  (LOSCFG_PLATFORM_HWI_LIMIT + CLINT_IRQ_NUM)

#define METAL_RISCV_PLIC0_C000000_BASE_ADDRESS      (0xC000000)
#define METAL_RISCV_PLIC0_ENABLE_BASE               (0x2000)
#define METAL_RISCV_PLIC0_PRIORITY_BASE             (0x0)
#define METAL_RISCV_PLIC0_CONTEXT_BASE              (0x200000)
#define METAL_RISCV_PLIC0_CONTEXT_CLAIM             (0x4)

#endif